services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
    image: portfolio:latest
    container_name: portfolio
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - NODE_ENV=production
